services:
  web:
    build: .
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - api-gateway
    networks:
      - app-network

networks:
  app-network:
    external: true